base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # INFO: Student Paths
    path("student/register", views.student_register, name="student/register"),
    path("student/enrollment", views.student_enrollment, name="student/enrollment"),
    path("student/course/", views.student_course, name="student/course"),
    path(
        "student/course/<str:pk>/assignment",
        views.student_assignment,
        name="student/assignment",
    ),
    path(
        "student/course/<str:course_pk>/assignment/<str:ass_pk>/submission",
        views.student_submissions,
        name="student/submission",
    ),
    path(
        "student/submission/<str:pk>/report",
        views.student_report,
        name="student/report",
    ),
    # INFO: Teacher Paths
    path("teacher/register", views.teacher_register, name="teacher/register"),
    path("teacher/course", views.teacher_course, name="teacher/course"),
    path(
        "teacher/create_course",
        views.teacher_create_course,
        name="teacher/create_course",
    ),
    path(
        "teacher/course/<str:pk>/assignment",
        views.teacher_assignment,
        name="teacher/assignment",
    ),
    path(
        "teacher/course/<str:course_pk>/assignment/create",
        views.teacher_create_assignment,
        name="teacher/create-assignment",
    ),
    path(
        "teacher/course/<str:pk>/assignment/<str:ass_pk>/submission",
        views.teacher_submissions,
        name="teacher/submissions",
    ),
    path("teacher/submission/<str:pk>/report", views.teacher_report, name="teacher/report"),
    # INFO: Auth Paths
    path("login/", views.login_register, name="login"),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.logout_route, name="logout"),
]

grading_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.utils.timezone import localtime, is_aware
from datetime import timedelta

# Create your models here.


class UserType(models.TextChoices):
    STUDENT = "ST", _("Student")
    TEACHER = "TE", _("Teacher")

    @staticmethod
    def get_link(data: str):
        match data:
            case "TE":
                return "teacher/course"
            case _:
                # By default return the student home
                return "student/course"

    @staticmethod
    def get_register_link(data: str):
        match data:
            case "TE":
                return "teacher/register"
            case _:
                # By default return the student home
                return "student/register"


class StudentLevel(models.IntegerChoices):
    LEVEL_100 = 100, _("100 Level")
    LEVEL_200 = 200, _("200 Level")
    LEVEL_300 = 300, _("300 Level")
    LEVEL_400 = 400, _("400 Level")
    LEVEL_500 = 500, _("500 Level")


class User(AbstractUser):
    # username = models.CharField(max_length=200)
    username = models.CharField(max_length=200)
    email = models.EmailField(unique=True)
    user_type = models.CharField(
        max_length=2, choices=UserType, default=UserType.STUDENT
    )

    def get_student(self) -> type["Student"]:
        return Student.objects.get(user=self)

    def get_teacher(self) -> type["Teacher"]:
        return Teacher.objects.get(user=self)

    REQUIRED_FIELDS = ["user_type"]
    USERNAME_FIELD = "email"


class Student(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, unique=True)
    level = models.IntegerField(
        choices=StudentLevel,
    )
    program = models.CharField(max_length=200)
    department = models.CharField(max_length=200)

    def get_name(self):
        return f"{str(self.user.last_name)} {str(self.user.first_name)}"

    def __str__(self):
        return str(self.user)


class Teacher(models.Model):
    department = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)


class Course(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField()
    students = models.ManyToManyField(Student, "enrollment_key")

    def __str__(self):
        return str(self.name)


# class Enrollment(models.Model):
#     course = models.ForeignKey(Course, on_delete=models.CASCADE)
#     student = models.ForeignKey(Student, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return f"{str(self.student)} -> {str(self.course)}"


class Assignment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    due_date = models.DateTimeField()
    name = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.name)

    def is_due(self) -> bool:
        time = timezone.now()
        due_date = self.due_date
        time = time + timedelta(hours=1)
        val = time > due_date

        print(val, time, due_date)
        return val


class Submission(models.Model):
    # INFO: When we delete an assignment from a course, don't delete the submission
    assignment = models.ForeignKey(
        Assignment, on_delete=models.SET_NULL, null=True)
    # INFO: When we delete a student, delete the submission
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    file_name = models.CharField(max_length=200)
    file = models.FileField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{str(self.student)} -> {str(self.file_name)}"


class Plagarism(models.Model):
    submission = models.ForeignKey(Submission, on_delete=models.CASCADE)
    sources = models.TextField(null=True)
    plagarized = models.BooleanField()
    sources_scores = models.TextField(max_length=2048)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.score)


class Similarity(models.Model):
    submission = models.ForeignKey(Submission, on_delete=models.CASCADE)
    score = models.FloatField()
    sources = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.score)


class Grading(models.Model):
    submission = models.ForeignKey(Submission, on_delete=models.CASCADE)
    predicted_score = models.FloatField()
    spelling_errors = models.FloatField()
    grammar_errors = models.FloatField()
    readability_score = models.FloatField()
    readability_level = models.TextField(max_length=256)
    topics_covered = models.TextField()
    description_match = models.TextField()
    total_score = models.FloatField()
    sources = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

base/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.contrib import messages
from .essay_model import predict_word as grading_predict
from .plagiarism_model import predict as plag_predict

from base.forms import (
    AssignmentCreationForm,
    CourseCreationForm,
    EnrollmentForm,
    RegisterUserForm,
    StudentRegistrationForm,
    SubmissionForm,
    TeacherRegistrationForm,
)

from . import models


# INFO: Student Routes
def student_course(request: HttpRequest):
    """{
    Get the all the courses for a student and put it in a list
    """
    user: models.Student = request.user.get_student()
    if not user:
        return HttpResponse(b"You are not logged in")

    courses = models.Course.objects.filter(students__id=user.id)

    ctx = {"courses": courses}
    return render(request, "base/students/course.html", ctx)


def student_register(request: HttpRequest):
    if not request.user.is_authenticated:
        return HttpResponse("You need to be logged in to get here")

    try:
        user = request.user.get_student()
        return HttpResponse("You already are a student")
    except:
        if request.method == "POST":
            form = StudentRegistrationForm(request.POST)
            if form.is_valid():
                student = form.save(commit=False)
                student.user = request.user
                student.save()
                form.save_m2m()
                return redirect("student/course")
            else:
                messages.error(
                    request, "An error occured trying to register the user")
        form = StudentRegistrationForm()
        ctx = {"form": form}
        return render(request, "base/students/register.html", ctx)


def student_enrollment(request: HttpRequest):
    student = request.user.get_student()
    if not student:
        return HttpResponse("Not a valid student")

    if request.method == "POST":
        enrollment_form = EnrollmentForm(request.POST)
        if enrollment_form.is_valid():
            course = models.Course.objects.get(id=request.POST.get("course"))

            course.students.add(student)
            return redirect("student/course")

    enrollment_form = EnrollmentForm()
    all_courses = models.Course.objects.all()
    courses_enrolled_in = models.Course.objects.filter(students=student)
    valid_courses = all_courses.difference(courses_enrolled_in)

    enrollment_form.fields["course"].queryset = valid_courses

    return render(
        request,
        "base/students/enrollment_form.html",
        {"valid_courses": valid_courses, "form": enrollment_form},
    )


def student_assignment(request: HttpRequest, pk: str):
    """
    Get all the assignment for course using the course_id(`pk`)
    """

    course = models.Course.objects.get(id=int(pk))
    assignments = models.Assignment.objects.filter(course__id=int(pk))
    print(assignments)
    submission = models.Submission.objects.filter(student__user=request.user)
    submitted_assignments = [
        submission.assignment for submission in submission]

    return render(
        request,
        "base/students/assignment.html",
        {
            "assignments": assignments,
            "course": course,
            "submitted_assignments": submitted_assignments,
        },
    )


def student_submissions(request: HttpRequest, course_pk: int, ass_pk: int):
    """
    Upload the submission
    """
    student = models.Student.objects.get(user=request.user)
    if not student:
        return HttpResponse(b"An error occured, the user was not defined")

    course = models.Course.objects.get(id=int(course_pk))
    assignment = models.Assignment.objects.get(id=int(ass_pk))

    try:
        prev_submission = models.Submission.objects.get(
            student=student, assignment=assignment
        )
        if prev_submission:
            return HttpResponse(b"You have already submitted before")
    except:
        if request.method == "POST":
            submission_form = SubmissionForm(request.POST, request.FILES)
            if submission_form.is_valid():
                submission = submission_form.save(commit=False)
                submission.assignment = assignment
                submission.student = student

                submission.save()
                submission_form.save_m2m()
                return redirect("student/course")
            else:
                return HttpResponse(b"There was an error in submitting the form")

        submission_form = SubmissionForm()
        ctx = {"course": course, "assignment": assignment,
               "form": submission_form}
        return render(request, "base/students/submission.html", ctx)


def student_report(request: HttpRequest, pk: int):
    """
    Get the submission report for a student assignment submission
    """
    submission = models.Submission.objects.get(id=pk)
    if not submission.assignment.is_due():
        return render("base/students/report.html", context={"is_due": submission.assignment.is_due()})

    user_content = open(submission.file.path).read()
    other_submissions = models.Submission.objects.filter(
        assignment=submission.assignment)
    other_submissions = list(filter(
        lambda x: x != submission, other_submissions))
    content = [open(submission.file.path).read()
               for submission in other_submissions]
    plagarism = None
    try:
        plagarism = models.Plagarism.objects.get(submission=submission)
    except:
        plag_stuff = plag_predict(user_content, content)
        (scores, plagarized) = plag_stuff
        scores = [str(score) for score in scores]

        students_copied_from = [
            str(submission.id) for submission in other_submissions]
        sources = ",".join(students_copied_from)
        plagarism = models.Plagarism.objects.create(sources_scores=",".join(
            scores), plagarized=plagarized, submission=submission, sources=sources)

    grading = None
    try:
        grading = models.Grading.objects.get(submission=submission)
    except:
        grading_stuff = grading_predict(
            user_content, 100, ["test topic"], "this is a test topic")
        if plagarism and plagarism.plagarized:
            grading_stuff["predicted_score"] -= 10
        grading = models.Grading.objects.create(
            **grading_stuff, submission=submission)
        grading.save()

    plag_sources = [models.Submission.objects.get(
        id=int(submission)) for submission in filter(lambda x: x != "", plagarism.sources.split(","))]
    plag_source_scores = plagarism.sources_scores.split(",")
    plag_data = zip(plag_sources, plag_source_scores)
    return render(request, "base/students/report.html", context={"is_due": false, "grading": grading, "plagarism": plagarism, "plag_data": plag_data})


# INFO: Teacher Routes
def teacher_register(request: HttpRequest):
    if not request.user.is_authenticated:
        return HttpResponse("You need to be logged in to get here")

    try:
        user = request.user.get_teacher()
        return HttpResponse("You already are a teacher")
    except:
        if request.method == "POST":
            form = TeacherRegistrationForm(request.POST)
            if form.is_valid():
                teacher = form.save(commit=False)
                teacher.user = request.user
                teacher.save()
                form.save_m2m()
                return redirect("teacher/course")
            else:
                messages.error(
                    request, "An error occured trying to register the user")
        form = TeacherRegistrationForm()
        ctx = {"form": form}
        return render(request, "base/teachers/register.html", ctx)


def teacher_course(request: HttpRequest):
    teacher = request.user.get_teacher()
    if teacher is None:
        return HttpResponse(b"User must be a teacher to use this route")
    courses = models.Course.objects.filter(teacher__id=teacher.id)
    ctx = {
        "courses": courses,
    }
    return render(request, "base/teachers/course.html", ctx)


def teacher_create_course(request: HttpRequest):
    teacher = request.user.get_teacher()
    if not teacher:
        return HttpResponse("Not a valid teacher")
    if request.method == "POST":
        course_form = CourseCreationForm(request.POST)
        if course_form.is_valid():
            course = course_form.save(commit=False)
            course.teacher = teacher
            course.save()
            course_form.save_m2m()
            return redirect("teacher/course")
        else:
            messages.error(
                request, "There was an error in creating a new course")

    course_form = CourseCreationForm()
    ctx = {"form": course_form}
    return render(request, "base/teachers/course_creation.html", ctx)


def teacher_create_assignment(request: HttpRequest, course_pk: str):
    teacher = request.user.get_teacher()
    if not teacher:
        return HttpResponse("Not a valid teacher")
    course = models.Course.objects.get(id=int(course_pk))
    if request.method == "POST":
        assignment_form = AssignmentCreationForm(request.POST)
        if assignment_form.is_valid():
            assignment = assignment_form.save(commit=False)
            assignment.course = course
            assignment.teacher = teacher
            assignment.save()
            assignment_form.save_m2m()
            return redirect("teacher/course")
        else:
            messages.error(
                request, "There was an error in creating a new course")

    assignment_form = AssignmentCreationForm()
    ctx = {"form": assignment_form, "course": course}
    return render(request, "base/teachers/assignment_creation.html", ctx)
    pass


def teacher_assignment(request: HttpRequest, pk: str):
    course = models.Course.objects.get(id=int(pk))
    print(course.assignment_set.count())

base/templates/base/teachers/assignment.html
{% extends 'base/dashboard teacher.html' %}

{% block title %} Course {% endblock title%}

{% block content %}

<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">

    <div class="card-body">
      <h4 class="card-title d-flex justify-content-between align-items-center">
        <span>Assignments for {{ course.name }}</span>
        <a href="{% url 'teacher/create-assignment' course.id %}"
          class="btn btn-block btn-gradient-primary btn-sm font-weight-medium auth-form-btn" type="submit">Add
          assignment</a>
      </h4>

      {% if assignments|length == 0 %}
      <h4 class="my-4 text-center">This course has no assignment</h3>

        {% else %}
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Assignment Name</th>
              <th>Assignment Description</th>
              <th>No of Submissions</th>
            </tr>
          </thead>
          <tbody>
            {% for assignment in assignments %}
            <tr>
              <td><a href="{% url 'teacher/submissions' course.id assignment.id %}">{{assignment.name}}</a></td>
              <td>{{assignment.description|truncatechars:50}}</td>
              <td>{{assignment.submission_set.count}}</td>
            </tr>

            {% endfor %}
          </tbody>
        </table>
        {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

base/templates/base/teachers/assignment_creation.html
{% extends "base/dashboard teacher.html" %}

{% block title %}
Assignment Creation
{% endblock title %}

{% block content %}
<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Add an assignment for {{course.name}}</h4>
      <form action="{% url 'teacher/create-assignment' course.id %}" method="post">
        {% csrf_token %}

        <div class="form-group">
          <p class="my-4">{{ form.name.label }}</p>
          {{ form.name }}
        </div>
        <div class="form-group">
          <p class="my-4">{{ form.description.label }}</p>
          {{ form.description }}
        </div>

        <div class="form-group">
          <p class="my-4">{{ form.due_date.label }}</p>
          <input type="datetime-local" class="form-control form-control-lg" name="due_date"
            placeholder="Enter Due Date">
        </div>
        <div>
          <button class="btn btn-block btn-gradient-primary btn-md font-weight-medium auth-form-btn"
            type="submit">Create</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

base/templates/base/teachers/course.html
{% extends 'base/dashboard teacher.html' %}

{% block title %} Course {% endblock title%}

{% block content %}

<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
      
    <div class="card-body">
<h4 class="card-title d-flex justify-content-between align-items-center">
  <span>My Courses</span>
    <a href="{% url 'teacher/create_course' %}" class="btn btn-block btn-gradient-primary btn-sm font-weight-medium auth-form-btn" type="submit">Create a new course</a>
</h4>

    {% if courses|length == 0 %}
    <h4 class="my-4 text-center">You haven't enrolled in any course</h3>
    
    {% else %}
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Course Name</th>
            <th>Course Description</th>
            <th>No of Students</th>
          </tr>
        </thead>
        <tbody>
          {% for course in courses %}
          <tr>
            <td><a href="{% url 'teacher/assignment' course.id %}">{{course.name}}</a></td>
            <td>{{course.description|truncatechars:50}}</td>
            <td>{{course.students.count}}</td>
          </tr>
          
          {% endfor %}
        </tbody>
      </table>
    {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

base/templates/base/teachers/course_creation.html
{% extends "base/dashboard teacher.html" %}

{% block title %}
Course Creation
{% endblock title %}

{% block content %}
<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
    <h4 class="card-title">Create a course</h4>
<form action="{% url 'teacher/create_course' %}" method="post">
  {% csrf_token %}
  
  {% for field in form  %}
  
  <div class="form-group">
    <p class="my-4">{{ field.label }}</p>
  {{ field }}
  </div>
  {% endfor %}
  <div>
    <button class="btn btn-block btn-gradient-primary btn-md font-weight-medium auth-form-btn" type="submit">Create</button>
  </div>
</form>
</div></div></div>
{% endblock content %}

base/templates/base/teachers/register.html
{% extends "base/auth.html" %} {% block auth_title %}
<span>Want to teach?</span>
{% endblock auth_title %} {% block auth_description %}

<span>Fill in your details to sign up as a teacher</span>

{% endblock auth_description %} {% block content %}
<form action="{% url 'teacher/register'  %}" method="post">
  {% csrf_token %} {% for field in form %}
  <div class="form-group">
    <p class="my-2">{{field.label}}</p>
    {{field}}
  </div>

  {% endfor %}

  <div class="mt-3">
    <button class="btn btn-block btn-gradient-primary btn-lg font-weight-medium auth-form-btn" type="submit">
      Continue
    </button>
  </div>
</form>

{% endblock content %}

base/templates/base/teachers/report.html
{% extends 'base/dashboard teacher.html' %}
{% block title %}
  Submission Report
{% endblock %}
{% block content %}
  <h1>Report Content for {{ grading.submission.student.user.first_name }}</h1>
  {% if is_due %}
    <p>Report cannot be shown because the assignment is not yet due</p>
  {% else %}
    <h3>Essay Grading</h3>
    <p>Predicted Essay Score: {{ grading.predicted_score }} {% if plagarism.plagarized %}<span class="text-danger">[Removed 10 marks due to plagarism]</span{% endif %}</p>
    <p>Spelling Errors: {{ grading.spelling_errors }}</p>
    <p>Grammar Errors: {{ grading.grammar_errors }}</p>
    <p>Readability Score: {{ grading.readability_score }}</p>
    <p>Readability Level: {{ grading.readability_level }}</p>

    <h3>Plagarism</h3>
    {% for submission, scores in plag_data %} 
    <p>{{ submission.student.user.first_name }}: {{ scores }}% </p>
    {% endfor %}
    <b>Is Plagarized: {{ plagarism.plagarized }}</b>
    {% comment %} <p>
      Plagarized: {{ plagarized }} <span class="text-red">({{ plagarism.score }})</span>
    </p> {% endcomment %}
  {% endif %}
{% endblock %}

base/templates/base/teachers/submissions.html
{% extends 'base/dashboard teacher.html' %}
{% block title %}
  Submissions
{% endblock %}
{% block content %}
  <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title d-flex justify-content-between align-items-center"><span>Submission for {{ assignment.name }}</span></h4>

        {% if submissions|length == 0 %}
          <h4 class="my-4 text-center">There haven't been any submission for the assignment</h4>
        {% else %}
          <table class="table table-hover">
            <thead>
              <tr>
                <th>File Name</th>
                <th>Student Name</th>
                <th>Submission Date</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {% for submission in submissions %}
                <tr>
                  <td>
                    <a href="{% url 'teacher/course' %}">{{ submission.file_name }}</a>
                  </td>
                  <td>{{ submission.student.get_name }}</td>
                  <td>{{ submission.created_at|date:'D d M Y' }} {{ submission.created_at|time:'H:i' }}</td>

                  <td>
                    {% if submission.assignment.is_due %}
                      <a href="{% url 'teacher/report' submission.id %}" class="">View Grading</a>
                    {% else %}
                      <a href="#" class="disabled nav-link-disabled" style="pointer-events: none; color: gray;" disabled>View Grading</a>
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}